# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: true

repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        types: [python]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [python]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        additional_dependencies: [cz-conventional-gitmoji]

  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.3.2
    hooks:
      - id: conventional-gitmoji

  - repo: https://github.com/pdm-project/pdm
    rev: 2.15.4
    hooks:
      - id: pdm-lock-check

  - repo: local
    hooks:
      - id: ruff
        name: Fix with ruff
        entry: ruff check
        args: ["--extend-fixable=ERA001,F401,F841"]
        require_serial: true
        language: system
        types: [python]

      - id: ruff
        name: Format with ruff
        entry: ruff format
        require_serial: true
        language: system
        types: [python]
