class TigerBeetleError(Exception): ...


class UnexpectedError(TigerBeetleError): ...


class OutOfMemoryError(TigerBeetleError): ...


class InvalidAddressError(TigerBeetleError): ...


class AddressLimitExceededError(TigerBeetleError): ...


class InvalidConcurrencyMaxError(TigerBeetleError): ...


class SystemResourcesError(TigerBeetleError): ...


class NetworkSubsystemError(TigerBeetleError): ...


class EmptyBatchError(TigerBeetleError): ...


class ClientClosedError(TigerBeetleError): ...


class ConcurrencyExceededError(TigerBeetleError): ...


class MaximumBatchSizeExceededError(TigerBeetleError): ...


class InvalidOperationError(TigerBeetleError): ...
